version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
       - dbdata:/var/lib/postgresql/data
  go:
    container_name: go
    ports:
      - "8081:8081"
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    depends_on:
      - "db"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    logging:
      options:
        max-size: "30m"
        max-file: "3"

volumes:
  dbdata:
  rabbitmq_data:  # Добавьте это